services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: ADMIN_IDS
        fromSecret: true
      - key: SUPPORT_USERNAME
        fromSecret: true